server:
  port: 8081
  address: localhost
logging:
  level:
    root: INFO
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/codewavedb2?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000